# Documentation: https://github.com/Genskao/MiningManager/#configuration
mining:
  interval: 10
  timeout: 15
  start: 10
  effect:
    smite: false
    explosion: true
  price: 100.0
scan:
  price: 10.0
regeneration:
  active: true
  interval: 30