name: MiningManager
main: fr.tropweb.miningmanager.MiningManager
version: "${project.fullVersion}"
author: Genskao
api-version: 1.13

commands:
  mm:
    description: All command for mining management
    usage: /<command> [scan|mine|reload|regenerate]