name: MiningManager
main: net.markpaj.miningmanager.MiningManager
version: "${project.fullVersion}"
author: MarkPaj
api-version: 1.13
softdepend:
  - "Vault"
  - "Towny"
commands:
  mm:
    description: All command for mining management
    usage: /<command> [scan|mine|reload|regenerate]